adding udp
rougeth/knocker pull request #3
Opened 2017-10-19 02:30 UTC by Guilhermeslucas

Solving issue #2

2018-03-05 13:02 UTC, rougeth requested changes
Sorry for the delay, completely forgot about this PR.

2018-03-05 13:02 UTC, rougeth commented on knocker.py
> +iimport argparse
typo

2018-03-05 13:02 UTC, rougeth commented on knocker.py
> +    if not(args.protocol.lower() == 'tcp' or args.protocol.lower() == 'udp'):
A better way to check the options would be this:`if args.protocol.lower() not in ['tcp', 'udb']`. But, argparse has a choices options: https://docs.python.org/3/library/argparse.html#choices.

2018-03-06 13:06 UTC, Guilhermeslucas commented
Done!

2018-03-11 23:18 UTC, rougeth commented
Sorry @Guilhermeslucas, I wasn't clear enough. `argparser` has an option called `choices`, you could do something like:

```python
parser.add_argument('-p', '--protocol', choices=['tcp', 'udb'], default='tcp')
```

Got it?

2018-03-17 23:46 UTC, Guilhermeslucas commented
Is this it?

2018-03-18 13:39 UTC, rougeth requested changes
Almost there, just those two comments and we're ready to merge.

2018-03-18 13:39 UTC, rougeth commented on knocker.py
> +    parser.add_argument('-p', '--protocol',choices=['tcp', 'udb'], default='tcp')
There is a typo here `udp`.

2018-03-18 13:39 UTC, rougeth commented on knocker.py
> +        exit()
You can remove this entire if, the `choices` argument already validate it.

2018-03-19 00:20 UTC, rougeth approved these changes

2018-03-19 00:20 UTC, merged